### ISSUE TITLE
sea-dragon .tumz

### ISSUE THREAD

**Issue by Nichalous** [Blue-Labs/DFW#2]
``` python
python -u /var/bluelabs/utils/blam.py --fore
 'version': 3}
21:48:56 I 0.0                   Server subject is '*.security-carpet.com'
21:48:56 I 0.0                   CAMS SSL certificate name matches
21:48:56 I 0.0                   Connected to CAMS
21:48:56 I 0.0                   prefs loaded
Traceback (most recent call last):
  File "/var/bluelabs/utils/blam.py", line 3450, in <module>
    main(rootlogger)
  File "/var/bluelabs/utils/blam.py", line 3309, in main
    logger=logger)
  File "/var/bluelabs/utils/dfw.py", line 224, in __init__
    filter_name = 'DFW:'+name
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by FirefighterBlu3** [comment]
fix committed in e2a700e
